// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication;

namespace WebApplication.Migrations
{
    [DbContext(typeof(QuotesDBContext))]
    partial class QuotesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("WebApplication.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("562a033c-01d7-4c58-bea5-f5e8ad92df66"),
                            Author = "Наполеон Хилл",
                            InsertDate = new DateTime(2021, 11, 5, 22, 55, 44, 589, DateTimeKind.Local).AddTicks(5309),
                            Text = "Что разум человека может постигнуть и во что он может поверить, того он способен достичь"
                        },
                        new
                        {
                            Id = new Guid("1befc933-04c3-44b3-87e8-49347faa29e5"),
                            Author = "Альберт Эйнштейн",
                            InsertDate = new DateTime(2021, 11, 5, 22, 55, 44, 591, DateTimeKind.Local).AddTicks(1477),
                            Text = "Стремитесь не к успеху, а к ценностям, которые он дает"
                        },
                        new
                        {
                            Id = new Guid("3f9f92a6-01b6-426c-9c7f-e2f07c741673"),
                            Author = "Флоренс Найтингейл",
                            InsertDate = new DateTime(2021, 11, 5, 22, 55, 44, 591, DateTimeKind.Local).AddTicks(1502),
                            Text = "Своим успехом я обязана тому, что никогда не оправдывалась и не принимала оправданий от других"
                        },
                        new
                        {
                            Id = new Guid("55252369-ce16-4f38-8894-5a77145a28d7"),
                            Author = "Амелия Эрхарт",
                            InsertDate = new DateTime(2021, 11, 5, 22, 55, 44, 591, DateTimeKind.Local).AddTicks(1507),
                            Text = "Сложнее всего начать действовать, все остальное зависит только от упорства"
                        },
                        new
                        {
                            Id = new Guid("744a2fba-ed26-4b7d-ae19-73c233219288"),
                            Author = "Федор Достоевский",
                            InsertDate = new DateTime(2021, 11, 5, 22, 55, 44, 591, DateTimeKind.Local).AddTicks(1509),
                            Text = "Надо любить жизнь больше, чем смысл жизни"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
